apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1 # Increase for HA/LB
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nanajanashia/k8s-demo-app:v1.0
        ports:
        - containerPort: 3000 # comes from Image Spec
        env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret # Secret File
              key: mongo-user # value for this key
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: mongo-secret # Secret File
              key: mongo-password # value for this key
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-url
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
  - protocol: TCP
    port: 3000 # best Practice: same as targetPort
    targetPort: 3000 # same as containerPort
    nodePort: 30100 # 30000 - 32767 -> Limited Port range by Kubernetes
